[package]
name = "ecdsa"
type = "bin"
authors = [""]

[dependencies]
noir_ecdsa = { tag = "v0.2.7", git = "https://github.com/zkpassport/noir-ecdsa" }
bignum = {tag = "v0.7.3-2", git = "https://github.com/zkpassport/noir-bignum"}
bigcurve = {tag = "v0.9.0-1", git = "https://github.com/zkpassport/noir_bigcurve"}
sha256 = { tag = "v0.1.4", git = "https://github.com/noir-lang/sha256" }